# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://mianmohammad.github.io/
baseurl: http://mianasif.info/
title: Mian Muhammad Asif Akhtar
author: Mian Muhammad Asif Akhtar
description: A full stak web developer
avatar: profilepic.jpg
email: se.mianasif@gmail.com
github: mianmohammad # username
twitter: se_mianasif
linkedin: mian-muhammad-asif-akhtar-43729872
stackoverflow: users/2125993/mian-muhammad-asif-akhtar   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: mianmuhammadasifakhtar
google_analytics: UA-52657949-2


# needed for travis-ci build
exclude: [vendor]
